name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt -y install git g++ cmake python3 valgrind gcovr libsqlite3-dev
    - name: Clone aquamarine repo
      run: git clone https://github.com/MaksymT17/aquamarine.git
    - name: Build artifacts with Cmake
      run: ./build.sh
