name: Linux build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: sudo apt -y install git g++ cmake libsqlite3-dev gcovr libjpeg-dev

    - name: Checkout aquamarine repo
      uses: actions/checkout@v4
      with:
        repository: MaksymT17/aquamarine
        ref: ${{ github.head_ref }}  # Use the head reference of the pull request
        path: aquamarine
        fetch-depth: 1

    - name: Build artifacts with Cmake
      run: |
        cd aquamarine &&
        ./build.sh

    - name: Run unit test
      run: |
        cd aquamarine/unit_tests &&
        ./prepare_build.sh &&
        cd build &&
        make -j8 &&
        ./aquamarine_ut --gtest_output="xml"

    - name: Publish Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Unit test results
        files: "**/test_detail.xml"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aquamarine_build_Linux
        path: aquamarine/build 
