name: Linux & Windows build check on master branch push event

on:
  push:
    branches: [ "master" ]

permissions:
  issues: write
  pull-requests: write
  checks: write

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt -y install git g++ cmake libsqlite3-dev gcovr libjpeg-dev
    - name: Clone aquamarine repo
      run: git clone https://github.com/MaksymT17/aquamarine.git
    - name: Build artifacts with Cmake
      run: |
        cd aquamarine &&
        ./build.sh

    - name: Run unit test
      run: |
        cd aquamarine/unit_tests &&
        ./prepare_build.sh &&
        cd build &&
        make -j8 &&
        ./aquamarine_ut --gtest_output="xml"

    - name: Publish Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Unit test results
        files: "**/test_detail.xml"

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone aquamarine repo
        run: git clone https://github.com/MaksymT17/aquamarine.git
        shell: bash

      - name: Build artifacts with Cmake
        run: |
          cd aquamarine &&
          echo "removing existing build folder..."
          rm -rf build/ &&
          mkdir build &&
          echo "preparing new build with cmake..." &&
          cd build/ &&
          cmake .. &&
          cmake --build . &&
          echo "Build complete!"
        shell: bash