name: Windows build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout aquamarine repo
        uses: actions/checkout@v4
        with:
          repository: MaksymT17/aquamarine
          ref: ${{ github.head_ref }}
          path: aquamarine
          fetch-depth: 1

      - name: Build artifacts with Cmake
        run: |
          cd aquamarine &&
          echo "removing existing build folder..."
          rm -rf build/ &&
          mkdir build &&
          echo "preparing new build with cmake..." &&
          cd build/ &&
          cmake -DCMAKE_BUILD_TYPE=Release .. &&
          cmake --build . &&
          echo "Build complete!"
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aquamarine_build_Windows
          path: aquamarine/build/