name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clone aquamarine repo
        run: git clone https://github.com/MaksymT17/aquamarine.git
      - name: Build artifacts with Cmake
        run: |
          cd aquamarine
          ./build.sh
